CUDA_VISIBLE_DEVICES=5,6 python3 train.py --embed_dim 256 \
                      --ff_embed_dim 1024 \
                      --num_heads 8 \
                      --layers 4 \
                      --dropout 0.0 \
                      --train_data data/toy\
                      --vocab data/toy_vocab\
                      --min_occur_cnt 50\
                      --batch_size 256\
                      --warmup_steps 10000\
                      --lr 1e-4\
                      --max_len 128\
                      --world_size 1\
                      --gpus 2\
                      --MASTER_ADDR localhost\
                      --MASTER_PORT 28000\
                      --start_rank 0\
                      --print_every 100\
                      --save_every 10000\
                      --save_dir ckpt\
                      --backend nccl
